### PR TITLE
Add Email To GitHub User Data

### PR DESCRIPTION
**Pull request by DmitryRomanenko**
Replaces #41: @taylorotwell asked to send it to 2.0, PSR-2 spaces.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
You need to keep the original authors.

**Comment by DmitryRomanenko** [comment]
It's my code from #40 with your brake statement, but all the lines are updated for PSR-2.

**Comment by GrahamCampbell** [comment]
@DmitryRomanenko You need to include my commit: https://github.com/laravel/socialite/commit/8906f6e53c3466d69397194eae5c89e4d62a0704.

**Comment by DmitryRomanenko** [comment]
I used another source commit to do it (597e923) because all the lines in this files were changed by Tylor.

**Comment by GrahamCampbell** [comment]
> because all the lines in this files were changed

That;s true. You're cs in this pull is wrong. It needs to be psr-2.

**Comment by DmitryRomanenko** [comment]
@GrahamCampbell I agree, could you give me an advice: how can I base pull-request code on both commits? (68db62661d20363d9c122ec1316918f611d81d2b and 8906f6e53c3466d69397194eae5c89e4d62a0704)?

**Pull request closed without merging**
