### PR TITLE
Added Instagram as a provider

### PR DESCRIPTION
**Pull request by hannesvdvreken**

### CODE REVIEW

**Comment by omairafzal** [comment]
Instagram basic scope is not supported now. Are you going to add the latest support for instagram or i can contribute with the new graph api support for instagram .

**Comment by driesvints** [comment]
@omairafzal https://socialiteproviders.netlify.com/providers/instagram.html

**Comment by omairafzal** [comment]
> @omairafzal https://socialiteproviders.netlify.com/providers/instagram.html

This doesnt work now beacuse of old apis of instagram

**Comment by driesvints** [comment]
@omairafzal feel free to send them a pr

**Comment by omair445** [comment]
Already sent bro

**Pull request closed without merging**
