### PR TITLE
Add getRaw method to the User contract

### PR DESCRIPTION
**Pull request by rihardssceredins**
Hey,

```php
use Laravel\Socialite\Contracts\User as SocialiteUser;

class LoginRequest extends FormRequest
{
    public function authorize()
    {
        return with(Socialite::driver('google')->user(), function (SocialiteUser $user) {
            return $user->getRaw()['hd'] === 'myorg.com';
        });
    }
}
```

I can use the public method `getRaw` on `AbstractUser` to get additional information about the user like in the case of Google his organization name but when using type hinting and static analysis (shout-out to Larastan 🚀) I get an error about accessing undefined method.

Can we add getRaw to the `Socialite\Contracts\User` contract?

### CODE REVIEW

**Comment by taylorotwell** [comment]
Can't on a patch release.

**Comment by rihardssceredins** [comment]
@taylorotwell does it mean I have to send it to master?

**Comment by driesvints** [comment]
@rihardssceredins imo this isn't needed. Just type-hint the concrete: `Laravel\Socialite\Two\User`.

**Comment by rihardssceredins** [comment]
@driesvints yeah did that after #498 was merged. Thanks! 👍🏼

**Pull request merged**
