### PR TITLE
Added BitBucket Provider

### PR DESCRIPTION
**Pull request by joecohens**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by DmitryRomanenko** [comment]
I think this provider should be in different repository because it's not popular with end users.

**Comment by joecohens** [comment]
I don't agree most services handling GitHub handle BitBucket also. Even Laravel Forge had lots of request one Taylor launched to support BitBucket.

**Comment by JulienTant** [comment]
I'm not sure it's a good idea to manage a lot of providers by default, because it's such a pain then to maintain every single provider changes.

**Comment by joecohens** [comment]
I guess you're right but the OAuth1 providers in this package are managed by https://github.com/thephpleague/oauth2-client https://github.com/laravel/socialite/blob/2.0/composer.json#L18

**Comment by GrahamCampbell** [comment]
I still think this provider is good to have in the core.

**Comment by antonioribeiro** [comment]
Bitbucket is the way to go if you need private repositories and cannot afford a Github private account. +1

**Comment by AndyWendt** [comment]
We added a bitbucket provider (as well as a ton of others) here: https://github.com/SocialiteProviders/BitBucket

**Comment by taylorotwell** [comment]
This could be sent to 2.0 branch.

**Comment by joecohens** [comment]
See https://github.com/laravel/socialite/pull/54

**Pull request closed without merging**
