### PR TITLE
Added setRedirectUrl method for dynamic URL redirection

### PR DESCRIPTION
**Pull request by KerryJones**
I am using the same configuration on different parts of an application and needed it to be redirected to different locations. I checked forums and it seems this feature was requested elsewhere as well:
http://stackoverflow.com/questions/30487429/laravel-5-and-socialite-new-redirect-after-login

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I don't think this should be allowed. It makes more sense to have it immutable.

**Comment by KerryJones** [comment]
Why should it be immutable? I gave a very plausible scenario (admin. vs main website) where it needs to be a different URL for each scenario. There is no other way to currently change the configuration or redirection.

**Comment by taylorotwell** [comment]
I would just call it `redirectUrl`. Drop the `set`.

**Comment by KerryJones** [comment]
Updated

**Comment by himinat** [comment]
Is there any way to use `'facebook' => [
       ...,
        'redirect' => route('routeName', ['params']),`

**Comment by GrahamCampbell** [comment]
> Why should it be immutable? I gave a very plausible scenario (admin. vs main website)

Should be implemented with two different objects.

**Comment by KerryJones** [comment]
Graham, do you have an example?

Taylor -- let me know if there is anything else you want me to do.

**Comment by claudiomedina** [comment]
Can we have this method for Oauth1 to?

**Comment by paulocastellano** [comment]
@taylorotwell and @KerryJones

The **redirectUrl** still working?

Because if I run:

```
return Socialite::driver('google')
            ->redirectUrl("http://localhost:8000/p/auth/login/google/callback")
            ->redirect();
```

I got error:

```
Client error: `POST https://www.googleapis.com/oauth2/v4/token` resulted in a `400 Bad Request` response: { "error": "redirect_uri_mismatch", "error_description": "Bad Request" }
```

**Comment by oza75** [comment]
@paulocastellano You should also set the redirect URL on the callback route when you retrieve user data
```php
$user = Socialite::driver('google')
           ->redirectUrl("http://localhost:8000/p/auth/login/google/callback")
            ->user();
```

**Pull request merged**
