### PR TITLE
Replaced deprecated app property in SocialiteManager

### PR DESCRIPTION
**Pull request by ctwillie**
…Manger class

### CODE REVIEW

**Comment by driesvints** [comment]
We'll need to convert the array access calls to `make` method calls because the container doesn't implements `ArrayAccess`.

**Comment by ctwillie** [comment]
I believe it does. According to the api docs.

https://laravel.com/api/7.x/Illuminate/Container/Container.html

**Comment by ctwillie** [comment]
@driesvints 

also try this

```php

$relectionContainer = new ReflectionClass(get_class(app()));

dd(relectionContainer->getInterfaceNames());
```
And you will see 'ArrayAccess' in the list

**Comment by driesvints** [comment]
@ctwillie that's the implementation. The property references the contract which doesn't implements it.

**Comment by ctwillie** [comment]
@driesvints Aha! Something I'll keep in mind from here on out. Thanks. Will do a PR.

**Comment by GrahamCampbell** [comment]
@ctwillie those are not the docs for the container contract though. ;)

https://laravel.com/api/7.x/Illuminate/Contracts/Container/Container.html

**Comment by ctwillie** [comment]
@GrahamCampbell  yea, I realize that now. I learned something new to pay attention to and stand corrected. Give me a break, I've only been coding for a couple of years, lol. Thanks for pointing that out though.

**Comment by driesvints** [comment]
@ctwillie we had to revert this because it broke apps running on Laravel 5.7 & 5.8. We can do these changes on master where only Laravel 6 and 7 are supported.

https://github.com/laravel/socialite/pull/450

**Comment by ctwillie** [comment]
Ok cool. Will do the same in master branch.

**Pull request merged**
