### PR TITLE
Update GoogleProvider to new Google API and scopes

### PR DESCRIPTION
**Pull request by CupOfTea696**
Current API is deprecated as noted in [OAuth2LoginV1](https://developers.google.com/accounts/docs/OAuth2LoginV1)

Documentation on the new API can be found here [+/api/oauth](https://developers.google.com/+/api/oauth)

### CODE REVIEW

**Comment by craigcartmell** [comment]
I'm currently getting the following error attempting to use the GoogleProvider:

**ClientException in RequestException.php line 71:
Client error response [url] https://accounts.google.com/o/oauth2/token [status code] 401 [reason phrase] Unauthorized**

This is after the callback where I'm attempting to get the user object.

`\Socialize::with('google')->user()`

The github provider works fine however.

**Comment by joshhornby** [comment]
I am also seeing this error. Posting the new code didn't work either and still returned a 401

**Comment by jschutt** [comment]
@craigcartmell Did you ever get a solution to this issue? I just bumped in to the same thing.

**Comment by jschutt** [comment]
@craigcartmell Apparently I didn't have the Google + api properly enabled for my app. Once I enabled it I just had to make a few tweaks to the user object and it's working.

**Comment by shehi** [comment]
@jschutt Thanks man, you saved my day :) Was wondering why the hell Socialite stops working after v2.0.2 for Google.

**Pull request merged**
