### PR TITLE
Add Email To GitHub User Data

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Replaces #40 with some fixes and an early exit optimization.

### CODE REVIEW

**Comment by joecohens** [comment]
:+1:

**Comment by metekabak** [comment]
Will someone merge this solution? We still can't get github private email(s).

**Comment by IsraelOrtuno** [comment]
Have tried this code and works perfect, is it going to be merged?

**Comment by amirhabibzadeh** [comment]
It works great , thanks . is it going to be merged to the main repo?

**Comment by taylorotwell** [comment]
Probably should be sent to 2.0 branch.

**Comment by DmitryRomanenko** [comment]
Why not to master?
Github provider doesn't work without this patch (email is always null).

**Comment by taylorotwell** [comment]
Because master isn't the current release? 2.0 is.

**Comment by taylorotwell** [comment]
Can someone re-target this?

**Comment by DmitryRomanenko** [comment]
@taylorotwell I will create a new one from scratch (because code style has been changed) and I'll target it to 2.0.

**Comment by GrahamCampbell** [comment]
You should retain the original commits.

**Comment by DmitryRomanenko** [comment]
> You should retain the original commits.
I won't use that commits or code from these commits.

**Comment by DmitryRomanenko** [comment]
> You should retain the original commits.

The problem is I don't know how to retain original commits because I want to use a new base commit (it's better to start with current 2.0 branch).

**Pull request closed without merging**
