### PR TITLE
Added Twitch driver

### PR DESCRIPTION
**Pull request by 0plus1**
Hi,

this pull request adds a fully functional Twitch provider.

Regards,

Davide

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Sorry, we're not accepting new providers here. Please see https://socialiteproviders.github.io/. I'm pretty sure there is already a Twitch driver there.

**Comment by 0plus1** [comment]
Hi Graham,

I understand, I wish I knew before :-D
It would be nice to add a link to socialiteproviders.github.io on the readme.md file :-)

Thanks for your great work,

Regards

**Comment by GrahamCampbell** [comment]
> It would be nice to add a link to socialiteproviders.github.io on the readme.md file :-)

That's not an "official" source though, so it wouldn't be politically correct for us to recommend it over someone else's packages.

**Comment by GrahamCampbell** [comment]
I have added this note though: https://github.com/laravel/socialite/pull/154.

**Comment by taylorotwell** [comment]
We let the community manage additional drivers through other repos.

**Pull request closed without merging**
