### PR TITLE
Google apps support

### PR DESCRIPTION
**Pull request by spamoom**
Tried to copy the code style best I could :)

The user only needs to (optionally) add

```
'apps_domain' => 'laravel.com',
```
to their config to force login with a google apps domain.

### CODE REVIEW

**Comment by taylorotwell** [comment]
You can use SocialiteManager::extend to add your own extensions to the library.

**Comment by spamoom** [comment]
@taylorotwell Had already done - thought it'd be a welcome addition as I'm not adding a new provider :)

**Comment by AndyWendt** [comment]
@spamoom checkout http://socialiteproviders.github.io/#providers 

We have a bunch of providers and an easy system for adding them.  If you want to send us a new one just send a PR to the https://github.com/SocialiteProviders/NewProvider repo

**Comment by spamoom** [comment]
@AndyWendt awesome! Thanks

**Pull request closed without merging**
