### PR TITLE
[4.0] Prepare for Laravel 6.0 release

### PR DESCRIPTION
**Pull request by driesvints**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Is it not wrong to allow installation on Laravel 7, when it may not actually be compatible?

**Comment by driesvints** [comment]
@grahamcampbell this is the only way for apps who use socialite and want to test v7.0 already to do that. We always make sure the builds for next releases are passing (as I did today) before doing a major release

**Comment by GrahamCampbell** [comment]
> this is the only way for apps who use socialite and want to test v7.0 already to do that. 

It's not the only way. You can just require Laravel 7 and tell composer you want to pretend it's Laravel 6 using the "as" notation. That happens in your app composer.json, which is much better than having incorrect version constraits out there in wild. You might as well just put `*` for the version, otherwise. :P

**Comment by driesvints** [comment]
@GrahamCampbell Taylor prefers it this way.

**Comment by GrahamCampbell** [comment]
:/

**Comment by GrahamCampbell** [comment]
Defeats the object of vesion constraints.

**Pull request merged**
