### PR TITLE
[5.x] Update LinkedInProvider.php

### PR DESCRIPTION
**Pull request by moha-ep**
Add vanityName on query to get the "nickname"

### CODE REVIEW

**Comment by driesvints** [comment]
Can you fix the test suite please?

**Comment by moha-ep** [comment]
> Can you fix the test suite please?  
My changes are based on the Linkedin documentation https://learn.microsoft.com/en-us/linkedin/shared/integrations/people/profile-api

I don't know why the tests are failing

**Comment by driesvints** [comment]
I fixed these for you and will let @taylorotwell review now.

**Comment by moha-ep** [comment]
> I fixed these for you and will let @taylorotwell review now.

That change you have made I already did last week, I just did not modify the tests, but thank you very much for the change waiting for the revision to be done 
ClipWindowsGIF

**Pull request merged**
