### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by romaldyminaya**
Updated for using with OctoberCMS plugin created by me.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
What?

**Comment by romaldyminaya** [comment]
@GrahamCampbell sorry, I tryed to merge to my own repository not yours, close this pull request @GrahamCampbell

**Comment by GrahamCampbell** [comment]
Can you close it please.

**Comment by romaldyminaya** [comment]
@GrahamCampbell yes, I really apologize for this :(

**Comment by GrahamCampbell** [comment]
No worries. :)

**Pull request closed without merging**
