### PR TITLE
Added types. Fixed consistency. Updated composer and GitHub actions

### PR DESCRIPTION
**Pull request by SuperDJ**
- Added types where possible
- Fixed test name consistency
- Updated composer package versions and GitHub test actions accordingly

### CODE REVIEW

**Comment by driesvints** [comment]
Thanks but sorry, this is way too much for us to review. We don't use most of the things that got changed here.

**Comment by SuperDJ** [comment]
@driesvints would you possibly accept it if there are multiple smaller PRs? 
Could you clarify what you mean with the following?
>We don't use most of the things that got changed here.

**Comment by driesvints** [comment]
Right now we don't have plans on doing any of these changes, sorry.

**Comment by SuperDJ** [comment]
@driesvints is this still not usable for Laravel 10?

**Comment by driesvints** [comment]
No, we have no plans to add types to our codebases. Only on stubs.

**Pull request closed without merging**
