### PR TITLE
Update AbstractProvider.php

### PR DESCRIPTION
**Pull request by alihossein**
The alignment of these three lines of code

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Sorry, these changes are incorrect. Please close this.

**Comment by alihossein** [comment]
why incorrect ?

**Comment by GrahamCampbell** [comment]
if this was merged, our automated system could revert it because all the changes are wrong

**Comment by GrahamCampbell** [comment]
https://styleci.io/analyses/z4xnae

**Comment by alihossein** [comment]
ok thanks

**Pull request closed without merging**
