### PR TITLE
Add Oauth2 GitlabProvider

### PR DESCRIPTION
**Pull request by jasonmccreary**

### CODE REVIEW

**Comment by AndyWendt** [comment]
@jasonmccreary I'm not sure that they want to add Gitlab as a default option.  You are more than welcome to submit it here however: http://socialiteproviders.github.io/

**Comment by taylorotwell** [comment]
Yeah would you mind submitting it to that collection of third-party providers. Surprised it wasn't already in there.

**Comment by jasonmccreary** [comment]
Sure thing. I wasn't aware of this collection. To that point, does this project `README` or Laravel Docs reference it?

**Comment by AndyWendt** [comment]
I'm not aware of any reference.

**Comment by jasonmccreary** [comment]
To close this out, I'd suggest adding such a reference in the `README` of Socialite or the Laravel Docs to the Socialite Providers collection so people know where to find more providers, as I definitely would have checked there before writing my own.

**Comment by GrahamCampbell** [comment]
Those providers arn't official or really associated with laravel though, so I think that would be inappropriate.

**Comment by jasonmccreary** [comment]
Fair. I think I'm just confused on where the line is drawn between *core* vs *third-party* providers. I just wanted to share this GitLab provider with others ;)

**Pull request closed without merging**
