### PR TITLE
getBody() return a Stream, so cast it to string

### PR DESCRIPTION
**Pull request by dlnsk**
Guzzle implements PSR-7. That means that it will by default store the body of a message in a Stream that uses PHP temp streams. To retrieve all the data, you can use casting operator or getContent() method.
http://stackoverflow.com/questions/30549226/guzzlehttp-how-get-the-body-of-a-response-from-guzzle-6

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Failing tests.

**Comment by dlnsk** [comment]
@GrahamCampbell of course, because test don't use real request.
Sorry, but I'm newbie in tests...

**Comment by taylorotwell** [comment]
So you're saying socialite? doesn't work at all right now?

**Comment by dlnsk** [comment]
@taylorotwell yes

**Comment by taylorotwell** [comment]
Just tested it. It's working fine for me with latest Socialite and Guzzle.

**Comment by GrahamCampbell** [comment]
This PR is broken on guzzle 5 anyways.

**Comment by dlnsk** [comment]
Sorry guys! I test it again and it works well. It's my own fault...

**Pull request closed without merging**
