### PR TITLE
Add Email To GitHub User Data

### PR DESCRIPTION
**Pull request by DmitryRomanenko**
Github didn't return email field before.

Even if $scopes has user:email entry.

Replaces #40, #41

### CODE REVIEW

**Comment by taylorotwell** [comment]
In my tests it does: http://d.pr/i/FaCk/1YabVHQD

Do I need to do something special to make it not return the e-mail address?

**Comment by DmitryRomanenko** [comment]
Github:
g1795047@trbvm.com
111222zzz

I've just created a new login and it doesn't have any email field.
Also it doesn't have a name.

**Comment by taylorotwell** [comment]
E-Mail still returns as `null` even after applying your changes.

**Comment by GrahamCampbell** [comment]
@taylorotwell My original pull worked fine?

**Comment by GrahamCampbell** [comment]
We were using it in prod on styleci for a while.

**Comment by dexbarrett** [comment]
@taylorotwell @GrahamCampbell @DmitryRomanenko I don't know if this is the case, but I noticed before that new GitHub accounts have the email set to hidden by default. I think that's why yours might be returning null. It happened to me and I just set it to be visible on the profile settings https://github.com/settings/profile

**Comment by dimsav** [comment]
> Some GitHub accounts have the email set to hidden.

I confirm that when the email is set to hidden, the API doesn't provide the email of the user.

**Comment by GrahamCampbell** [comment]
>  the API doesn't provide the email of the user.

It does if you set the correct scopes.

**Comment by sitesense** [comment]
I confirm the error. With existing code I get this on the callback:
~~~
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'email' cannot be null (SQL: insert into `users` (`name`, `email`, `password`, `updated_at`, `created_at`) values (Mark, , yURj/23m3ZUxmsl/9JYIrunz4GADGvfapXxGxXTtPEVumbLR2v2sq, 2015-05-07 22:55:03, 2015-05-07 22:55:03))
~~~
DmitryRomanenko's patch works for me.

**Pull request merged**
