### PR TITLE
Add Twitch driver

### PR DESCRIPTION
**Pull request by migueljteixeira**
Added the Twitch driver.

I hope it's everything ok ;)
Thanks,
Miguel

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by GrahamCampbell** [comment]
This already exists at https://github.com/SocialiteProviders/Twitch.

**Comment by taylorotwell** [comment]
See above.

**Comment by migueljteixeira** [comment]
Oh sorry :/

**Pull request closed without merging**
