### PR TITLE
Added Dropbox support

### PR DESCRIPTION
**Pull request by soutoner**
Dropbox provider created and its instance creator. In bold attributes that are provided:

* **ID**
* **Email**
* **Name**
* Avatar
* Nickname

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by GrahamCampbell** [comment]
This already exists as a third party extention.

**Comment by soutoner** [comment]
I have just seen that you're not interested in having Dropbox in this package, and @jasonvarga already tried to add it.

Sorry for colaborating.

**Comment by GrahamCampbell** [comment]
There are already hundreds of socialite drivers available. Just not in this package.

**Comment by GrahamCampbell** [comment]
https://github.com/SocialiteProviders

**Comment by soutoner** [comment]
Ok, it would be interesting to put some info about that repo in the documentation in order to guide people about how to contribute.

**Comment by GrahamCampbell** [comment]
Those repos are nothing to do with us though, and are not officially endorsed. It's up to you to google "laravel socialte dropbox" and click any link on the first page...

**Comment by soutoner** [comment]
I will do it next time.

**Pull request closed without merging**
