### PR TITLE
Change Google+ APIs because it will be shutdown

### LINKED ISSUE #317: [v3] Google+ APIs being shutdown
Hi,

I'm still using laravel 5.4 for php version reason. But, I got an email which saying that Google+ APIs being shutdown. But, unfortunately the changes are made for v4. Could you help me how I can use the changes which made in #283 for v3 ?

Thanks

### PR DESCRIPTION
**Pull request by saputradharma**
Fix Google+ APIs being shutdown #317, actually just take changes from here https://github.com/laravel/socialite/pull/283

### CODE REVIEW

**Comment by arborrow** [comment]
Quick question, I have a Laravel 5.6 site using socialite. When I run a composer update I am getting v3.2.0 which does not have the updates from this pull request I'm curious about the best way for me to be prepared for the Google+ API being shutdown. Is the plan to merge these changes into a new tag, such as v3.3.0 so that I can simply do a composer update and expect things to work or should I update composer json to specifically make use of the 3.0 branch. Looking at https://github.com/laravel/socialite/compare/v3.2.0...3.0 it seems that there are other changes that have not been pulled into latest tagged version and thus excluded from being implemented on my site (if I am understanding the proper flow of things).

**Comment by arborrow** [comment]
@driesvints thanks, specifying 3.0.x-dev in composer.json worked perfectly. Just for the sake of documentation, I was checking the user's domain using the Google+ API user['domain']; however, the People API uses user['hd']. Once I cleaned up my references to domain to hd in my code everything else seemed to work just fine and I was able to disable the Google+ API.

**Comment by rajjanorkar** [comment]
@taylorotwell - please release this change google+ api change as next minor version so we can pull it through composer.

Anyways google+ api is shutting down, so its not gonna work.

**Comment by driesvints** [comment]
@rajjanorkar please read my comment here: https://github.com/laravel/socialite/pull/319#issuecomment-450829869

**Pull request merged**
