### PR TITLE
Add Windows Live Connect provider to Socialite

### PR DESCRIPTION
**Pull request by bmwalter68**
I've added a Windows Live Connect OAuth2 provider to Socialite based on the code from the other OAuth2 providers.  Thanks for Laravel and Socialite Tyler!

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I doubt this will be accepted. Please contribute to the vast library of socialite providers out there already.

**Comment by GrahamCampbell** [comment]
https://github.com/SocialiteProviders

**Comment by GrahamCampbell** [comment]
Infact, I think one already exists. See https://github.com/SocialiteProviders/Microsoft-Live.

**Comment by bmwalter68** [comment]
Sorry for that, I'm coming from the wild and wooly world of Laravel 4 OAuth.  I was surprised at how few provers there were, but I must have missed the section of documentation where it explained how to extend Socialite or the existence of extension providers.  Is that in the primary Laravel documentation?

**Pull request closed without merging**
