### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by Renfos**
thephpleague/oauth1-client bug fixes.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by GrahamCampbell** [comment]
Please read composer's docs on what `~` means before sending a PR.

**Comment by taylorotwell** [comment]
Graham give a real response please.

**Comment by GrahamCampbell** [comment]
`~1.6` resolves the same version as `~1.0` would so this change doesn't do anything.

**Comment by taylorotwell** [comment]
Yeah @Renfos Graham is pretty much correct here. ~1.0 will still install anything up to 2.0 (not including 2.0).

**Pull request closed without merging**
